development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:4b7168f48dcc4604c4f6151d9dfbb990@spinyfin.redistogo.com:9779/
  channel_prefix: commerce_webapp_production
